[2025-08-07T02:58:03.983+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-07T02:58:04.069+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_transform_topcv.submit_spark_job manual__2025-08-07T02:57:57.655584+00:00 [queued]>
[2025-08-07T02:58:04.079+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_transform_topcv.submit_spark_job manual__2025-08-07T02:57:57.655584+00:00 [queued]>
[2025-08-07T02:58:04.080+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-07T02:58:04.096+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2025-08-07 02:57:57.655584+00:00
[2025-08-07T02:58:04.118+0000] {standard_task_runner.py:63} INFO - Started process 47 to run task
[2025-08-07T02:58:04.157+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_transform_topcv', 'submit_spark_job', 'manual__2025-08-07T02:57:57.655584+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_jobs_dag.py', '--cfg-path', '/tmp/tmpbdcapxwz']
[2025-08-07T02:58:04.176+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask submit_spark_job
[2025-08-07T02:58:04.447+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_transform_topcv.submit_spark_job manual__2025-08-07T02:57:57.655584+00:00 [running]> on host 986114d90a48
[2025-08-07T02:58:04.769+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_transform_topcv' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-08-07T02:57:57.655584+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-07T02:57:57.655584+00:00'
[2025-08-07T02:58:04.774+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-07T02:58:04.887+0000] {spark_submit.py:223} INFO - Could not load connection string spark_default, defaulting to yarn
[2025-08-07T02:58:04.889+0000] {spark_submit.py:351} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=minioadmin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --jars /opt/custom-jars/hadoop-aws-3.3.2.jar,/opt/custom-jars/aws-java-sdk-bundle-1.12.367.jar --name arrow-spark --verbose /opt/spark-jobs/gold_transform.py
[2025-08-07T02:58:06.346+0000] {spark_submit.py:521} INFO - WARNING: Using incubator modules: jdk.incubator.vector
[2025-08-07T02:58:08.870+0000] {spark_submit.py:521} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2025-08-07T02:58:08.871+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:640)
[2025-08-07T02:58:08.872+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:287)
[2025-08-07T02:58:08.872+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:245)
[2025-08-07T02:58:08.873+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:104)
[2025-08-07T02:58:08.873+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1101)
[2025-08-07T02:58:08.873+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1101)
[2025-08-07T02:58:08.874+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:72)
[2025-08-07T02:58:08.874+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1132)
[2025-08-07T02:58:08.875+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1141)
[2025-08-07T02:58:08.875+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-08-07T02:58:08.897+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-07T02:58:08.910+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 452, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=minioadmin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --jars /opt/custom-jars/hadoop-aws-3.3.2.jar,/opt/custom-jars/aws-java-sdk-bundle-1.12.367.jar --name arrow-spark --verbose /opt/spark-jobs/gold_transform.py. Error code is: 1.
[2025-08-07T02:58:08.918+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spark_transform_topcv, task_id=submit_spark_job, run_id=manual__2025-08-07T02:57:57.655584+00:00, execution_date=20250807T025757, start_date=20250807T025804, end_date=20250807T025808
[2025-08-07T02:58:08.942+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task submit_spark_job (Cannot execute: spark-submit --master yarn --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=minioadmin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --jars /opt/custom-jars/hadoop-aws-3.3.2.jar,/opt/custom-jars/aws-java-sdk-bundle-1.12.367.jar --name arrow-spark --verbose /opt/spark-jobs/gold_transform.py. Error code is: 1.; 47)
[2025-08-07T02:58:08.974+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-07T02:58:09.004+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-07T02:58:09.007+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
