[2025-08-08T03:42:48.471+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-08T03:42:48.512+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_transform_topcv.submit_spark_job manual__2025-08-08T03:42:44.209761+00:00 [queued]>
[2025-08-08T03:42:48.519+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_transform_topcv.submit_spark_job manual__2025-08-08T03:42:44.209761+00:00 [queued]>
[2025-08-08T03:42:48.520+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-08T03:42:48.531+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2025-08-08 03:42:44.209761+00:00
[2025-08-08T03:42:48.536+0000] {standard_task_runner.py:63} INFO - Started process 1611 to run task
[2025-08-08T03:42:48.540+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_transform_topcv', 'submit_spark_job', 'manual__2025-08-08T03:42:44.209761+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/etl_jobs_dag.py', '--cfg-path', '/tmp/tmpmx86fzc4']
[2025-08-08T03:42:48.542+0000] {standard_task_runner.py:91} INFO - Job 131: Subtask submit_spark_job
[2025-08-08T03:42:48.607+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_transform_topcv.submit_spark_job manual__2025-08-08T03:42:44.209761+00:00 [running]> on host 0d9cbc3d310d
[2025-08-08T03:42:48.769+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_transform_topcv' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-08-08T03:42:44.209761+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-08T03:42:44.209761+00:00'
[2025-08-08T03:42:48.770+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-08T03:42:48.803+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2025-08-08T03:42:48.804+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-08T03:42:48.804+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 155, in execute
    self._hook = self._get_hook()
                 ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 164, in _get_hook
    return SparkSubmitHook(
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 158, in __init__
    self._connection = self._resolve_connection()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 215, in _resolve_connection
    raise RuntimeError(
RuntimeError: The `spark-home` extra is not allowed any more. Please make sure one of ['spark-submit', 'spark2-submit', 'spark3-submit'] is available on the PATH, and set `spark-binary` if needed.
[2025-08-08T03:42:48.816+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spark_transform_topcv, task_id=submit_spark_job, run_id=manual__2025-08-08T03:42:44.209761+00:00, execution_date=20250808T034244, start_date=20250808T034248, end_date=20250808T034248
[2025-08-08T03:42:48.828+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 131 for task submit_spark_job (The `spark-home` extra is not allowed any more. Please make sure one of ['spark-submit', 'spark2-submit', 'spark3-submit'] is available on the PATH, and set `spark-binary` if needed.; 1611)
[2025-08-08T03:42:48.872+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-08T03:42:48.907+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-08T03:42:48.910+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
