[2025-09-09T09:00:01.772+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-09T09:00:01.810+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_transform_pipeline.silver_topcv_transform manual__2025-09-09T08:59:56.717591+00:00 [queued]>
[2025-09-09T09:00:01.818+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_transform_pipeline.silver_topcv_transform manual__2025-09-09T08:59:56.717591+00:00 [queued]>
[2025-09-09T09:00:01.820+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-09T09:00:01.831+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): silver_topcv_transform> on 2025-09-09 08:59:56.717591+00:00
[2025-09-09T09:00:01.841+0000] {standard_task_runner.py:63} INFO - Started process 205 to run task
[2025-09-09T09:00:01.847+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_transform_pipeline', 'silver_topcv_transform', 'manual__2025-09-09T08:59:56.717591+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/etl_jobs_dag.py', '--cfg-path', '/tmp/tmpo44p91d0']
[2025-09-09T09:00:01.853+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask silver_topcv_transform
[2025-09-09T09:00:01.912+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_transform_pipeline.silver_topcv_transform manual__2025-09-09T08:59:56.717591+00:00 [running]> on host be62b23e6301
[2025-09-09T09:00:02.011+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_transform_pipeline' AIRFLOW_CTX_TASK_ID='silver_topcv_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-09T08:59:56.717591+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-09T08:59:56.717591+00:00'
[2025-09-09T09:00:02.012+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-09T09:00:15.915+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-09T09:00:15.917+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark-jobs/elt/transform/silver_topcv_transform.py", line 33, in silver_topcv_transform
    df = spark.read.parquet(f"s3a://{MINIO_BUCKET}/bronze/topcv/topcv_jobs.parquet")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/readwriter.py", line 642, in parquet
    return self._df(self._jreader.parquet(_to_seq(self._spark._sc, paths)))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/py4j/java_gateway.py", line 1362, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/errors/exceptions/captured.py", line 288, in deco
    raise converted from None
pyspark.errors.exceptions.captured.NumberFormatException: For input string: "60s"
[2025-09-09T09:00:15.954+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spark_transform_pipeline, task_id=silver_topcv_transform, run_id=manual__2025-09-09T08:59:56.717591+00:00, execution_date=20250909T085956, start_date=20250909T090001, end_date=20250909T090015
[2025-09-09T09:00:16.033+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 49 for task silver_topcv_transform (For input string: "60s"; 205)
[2025-09-09T09:00:16.080+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-09T09:00:16.111+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-09T09:00:16.181+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
