[2025-08-05T17:03:11.090+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-05T17:03:11.120+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_transform_gold.submit_gold_transform manual__2025-08-05T17:03:06.615904+00:00 [queued]>
[2025-08-05T17:03:11.128+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_transform_gold.submit_gold_transform manual__2025-08-05T17:03:06.615904+00:00 [queued]>
[2025-08-05T17:03:11.128+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-05T17:03:11.139+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): submit_gold_transform> on 2025-08-05 17:03:06.615904+00:00
[2025-08-05T17:03:11.144+0000] {standard_task_runner.py:63} INFO - Started process 163 to run task
[2025-08-05T17:03:11.148+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_transform_gold', 'submit_gold_transform', 'manual__2025-08-05T17:03:06.615904+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_jobs_dag.py', '--cfg-path', '/tmp/tmpmh1ib2ie']
[2025-08-05T17:03:11.150+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask submit_gold_transform
[2025-08-05T17:03:11.200+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_transform_gold.submit_gold_transform manual__2025-08-05T17:03:06.615904+00:00 [running]> on host a2763191a4ee
[2025-08-05T17:03:11.284+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_transform_gold' AIRFLOW_CTX_TASK_ID='submit_gold_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-08-05T17:03:06.615904+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-05T17:03:06.615904+00:00'
[2025-08-05T17:03:11.285+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-05T17:03:11.310+0000] {spark_submit.py:223} INFO - Could not load connection string spark_default, defaulting to yarn
[2025-08-05T17:03:11.311+0000] {spark_submit.py:351} INFO - Spark-Submit cmd: spark-submit --master yarn --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --verbose /opt/spark-jobs/gold_transform.py
[2025-08-05T17:03:11.751+0000] {spark_submit.py:521} INFO - WARNING: Using incubator modules: jdk.incubator.vector
[2025-08-05T17:03:14.133+0000] {spark_submit.py:521} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2025-08-05T17:03:14.135+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:640)
[2025-08-05T17:03:14.136+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:287)
[2025-08-05T17:03:14.137+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:245)
[2025-08-05T17:03:14.137+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:104)
[2025-08-05T17:03:14.138+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1101)
[2025-08-05T17:03:14.139+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1101)
[2025-08-05T17:03:14.139+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:72)
[2025-08-05T17:03:14.140+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1132)
[2025-08-05T17:03:14.140+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1141)
[2025-08-05T17:03:14.141+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-08-05T17:03:14.172+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-05T17:03:14.198+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 452, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --verbose /opt/spark-jobs/gold_transform.py. Error code is: 1.
[2025-08-05T17:03:14.212+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spark_transform_gold, task_id=submit_gold_transform, run_id=manual__2025-08-05T17:03:06.615904+00:00, execution_date=20250805T170306, start_date=20250805T170311, end_date=20250805T170314
[2025-08-05T17:03:14.247+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task submit_gold_transform (Cannot execute: spark-submit --master yarn --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --verbose /opt/spark-jobs/gold_transform.py. Error code is: 1.; 163)
[2025-08-05T17:03:14.294+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-05T17:03:14.431+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-05T17:03:14.434+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
