[2025-08-08T03:29:34.037+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-08T03:29:34.091+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_transform_topcv.submit_spark_job manual__2025-08-08T03:29:30.665069+00:00 [queued]>
[2025-08-08T03:29:34.100+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_transform_topcv.submit_spark_job manual__2025-08-08T03:29:30.665069+00:00 [queued]>
[2025-08-08T03:29:34.101+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-08T03:29:34.113+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2025-08-08 03:29:30.665069+00:00
[2025-08-08T03:29:34.120+0000] {standard_task_runner.py:63} INFO - Started process 1331 to run task
[2025-08-08T03:29:34.148+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_transform_topcv', 'submit_spark_job', 'manual__2025-08-08T03:29:30.665069+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/etl_jobs_dag.py', '--cfg-path', '/tmp/tmpwxfc5dpp']
[2025-08-08T03:29:34.166+0000] {standard_task_runner.py:91} INFO - Job 129: Subtask submit_spark_job
[2025-08-08T03:29:34.353+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_transform_topcv.submit_spark_job manual__2025-08-08T03:29:30.665069+00:00 [running]> on host 0d9cbc3d310d
[2025-08-08T03:29:34.543+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_transform_topcv' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-08-08T03:29:30.665069+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-08T03:29:30.665069+00:00'
[2025-08-08T03:29:34.544+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-08T03:29:34.600+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2025-08-08T03:29:34.601+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-08T03:29:34.602+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 155, in execute
    self._hook = self._get_hook()
                 ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 164, in _get_hook
    return SparkSubmitHook(
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 158, in __init__
    self._connection = self._resolve_connection()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 215, in _resolve_connection
    raise RuntimeError(
RuntimeError: The `spark-home` extra is not allowed any more. Please make sure one of ['spark-submit', 'spark2-submit', 'spark3-submit'] is available on the PATH, and set `spark-binary` if needed.
[2025-08-08T03:29:34.625+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spark_transform_topcv, task_id=submit_spark_job, run_id=manual__2025-08-08T03:29:30.665069+00:00, execution_date=20250808T032930, start_date=20250808T032934, end_date=20250808T032934
[2025-08-08T03:29:34.651+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 129 for task submit_spark_job (The `spark-home` extra is not allowed any more. Please make sure one of ['spark-submit', 'spark2-submit', 'spark3-submit'] is available on the PATH, and set `spark-binary` if needed.; 1331)
[2025-08-08T03:29:34.659+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-08T03:29:34.683+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-08T03:29:34.687+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
