[2025-08-07T18:02:27.710+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-07T18:02:27.892+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_transform_topcv.submit_spark_job manual__2025-08-07T18:02:19.243923+00:00 [queued]>
[2025-08-07T18:02:27.909+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_transform_topcv.submit_spark_job manual__2025-08-07T18:02:19.243923+00:00 [queued]>
[2025-08-07T18:02:27.931+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-07T18:02:28.022+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2025-08-07 18:02:19.243923+00:00
[2025-08-07T18:02:28.039+0000] {standard_task_runner.py:63} INFO - Started process 244 to run task
[2025-08-07T18:02:28.068+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_transform_topcv', 'submit_spark_job', 'manual__2025-08-07T18:02:19.243923+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/etl_jobs_dag.py', '--cfg-path', '/tmp/tmpbv1mcndu']
[2025-08-07T18:02:28.147+0000] {standard_task_runner.py:91} INFO - Job 89: Subtask submit_spark_job
[2025-08-07T18:02:28.782+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_transform_topcv.submit_spark_job manual__2025-08-07T18:02:19.243923+00:00 [running]> on host 0d9cbc3d310d
[2025-08-07T18:02:29.839+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_transform_topcv' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-08-07T18:02:19.243923+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-07T18:02:19.243923+00:00'
[2025-08-07T18:02:29.840+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-07T18:02:29.911+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2025-08-07T18:02:29.912+0000] {spark_submit.py:351} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=minioadmin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --conf spark.hadoop.fs.s3a.connection.ssl.enabled=false --conf spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider --conf spark.hadoop.fs.s3a.connection.timeout=60000 --conf spark.hadoop.fs.s3a.connection.establish.timeout=60000 --conf spark.hadoop.fs.s3a.connection.request.timeout=60000 --conf spark.hadoop.fs.s3a.attempts.maximum=20 --jars /opt/custom-jars/hadoop-aws-3.3.6.jar,/opt/custom-jars/aws-java-sdk-bundle-1.12.621.jar --name arrow-spark --verbose /opt/spark-jobs/gold_transform.py
[2025-08-07T18:02:31.587+0000] {spark_submit.py:521} INFO - WARNING: Using incubator modules: jdk.incubator.vector
[2025-08-07T18:02:33.136+0000] {spark_submit.py:521} INFO - Parsed arguments:
[2025-08-07T18:02:33.137+0000] {spark_submit.py:521} INFO - master                  spark://spark-master:7077
[2025-08-07T18:02:33.138+0000] {spark_submit.py:521} INFO - remote                  null
[2025-08-07T18:02:33.138+0000] {spark_submit.py:521} INFO - deployMode              null
[2025-08-07T18:02:33.138+0000] {spark_submit.py:521} INFO - executorMemory          null
[2025-08-07T18:02:33.138+0000] {spark_submit.py:521} INFO - executorCores           null
[2025-08-07T18:02:33.139+0000] {spark_submit.py:521} INFO - totalExecutorCores      null
[2025-08-07T18:02:33.139+0000] {spark_submit.py:521} INFO - propertiesFile          null
[2025-08-07T18:02:33.139+0000] {spark_submit.py:521} INFO - driverMemory            null
[2025-08-07T18:02:33.139+0000] {spark_submit.py:521} INFO - driverCores             null
[2025-08-07T18:02:33.140+0000] {spark_submit.py:521} INFO - driverExtraClassPath    null
[2025-08-07T18:02:33.140+0000] {spark_submit.py:521} INFO - driverExtraLibraryPath  null
[2025-08-07T18:02:33.140+0000] {spark_submit.py:521} INFO - driverExtraJavaOptions  null
[2025-08-07T18:02:33.140+0000] {spark_submit.py:521} INFO - supervise               false
[2025-08-07T18:02:33.141+0000] {spark_submit.py:521} INFO - queue                   null
[2025-08-07T18:02:33.141+0000] {spark_submit.py:521} INFO - numExecutors            null
[2025-08-07T18:02:33.141+0000] {spark_submit.py:521} INFO - files                   null
[2025-08-07T18:02:33.141+0000] {spark_submit.py:521} INFO - pyFiles                 null
[2025-08-07T18:02:33.142+0000] {spark_submit.py:521} INFO - archives                null
[2025-08-07T18:02:33.142+0000] {spark_submit.py:521} INFO - mainClass               null
[2025-08-07T18:02:33.142+0000] {spark_submit.py:521} INFO - primaryResource         file:/opt/spark-jobs/gold_transform.py
[2025-08-07T18:02:33.143+0000] {spark_submit.py:521} INFO - name                    arrow-spark
[2025-08-07T18:02:33.143+0000] {spark_submit.py:521} INFO - childArgs               []
[2025-08-07T18:02:33.143+0000] {spark_submit.py:521} INFO - jars                    file:/opt/custom-jars/hadoop-aws-3.3.6.jar,file:/opt/custom-jars/aws-java-sdk-bundle-1.12.621.jar
[2025-08-07T18:02:33.143+0000] {spark_submit.py:521} INFO - packages                null
[2025-08-07T18:02:33.143+0000] {spark_submit.py:521} INFO - packagesExclusions      null
[2025-08-07T18:02:33.144+0000] {spark_submit.py:521} INFO - repositories            null
[2025-08-07T18:02:33.144+0000] {spark_submit.py:521} INFO - verbose                 true
[2025-08-07T18:02:33.144+0000] {spark_submit.py:521} INFO - 
[2025-08-07T18:02:33.144+0000] {spark_submit.py:521} INFO - Spark properties used, including those specified through
[2025-08-07T18:02:33.145+0000] {spark_submit.py:521} INFO - --conf and those from the properties file null:
[2025-08-07T18:02:33.145+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.access.key,*********(redacted))
[2025-08-07T18:02:33.145+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.attempts.maximum,20)
[2025-08-07T18:02:33.145+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.aws.credentials.provider,org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider)
[2025-08-07T18:02:33.146+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.connection.establish.timeout,60000)
[2025-08-07T18:02:33.146+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.connection.request.timeout,60000)
[2025-08-07T18:02:33.146+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.connection.ssl.enabled,false)
[2025-08-07T18:02:33.147+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.connection.timeout,60000)
[2025-08-07T18:02:33.147+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.endpoint,http://minio:9000)
[2025-08-07T18:02:33.147+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.impl,org.apache.hadoop.fs.s3a.S3AFileSystem)
[2025-08-07T18:02:33.148+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.path.style.access,true)
[2025-08-07T18:02:33.148+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.secret.key,*********(redacted))
[2025-08-07T18:02:33.149+0000] {spark_submit.py:521} INFO - 
[2025-08-07T18:02:33.149+0000] {spark_submit.py:521} INFO - 
[2025-08-07T18:02:33.775+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:33 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-08-07T18:02:34.128+0000] {spark_submit.py:521} INFO - Main class:
[2025-08-07T18:02:34.129+0000] {spark_submit.py:521} INFO - org.apache.spark.deploy.PythonRunner
[2025-08-07T18:02:34.130+0000] {spark_submit.py:521} INFO - Arguments:
[2025-08-07T18:02:34.130+0000] {spark_submit.py:521} INFO - file:/opt/spark-jobs/gold_transform.py
[2025-08-07T18:02:34.130+0000] {spark_submit.py:521} INFO - null
[2025-08-07T18:02:34.132+0000] {spark_submit.py:521} INFO - Spark config:
[2025-08-07T18:02:34.132+0000] {spark_submit.py:521} INFO - (spark.app.name,arrow-spark)
[2025-08-07T18:02:34.133+0000] {spark_submit.py:521} INFO - (spark.app.submitTime,1754589754093)
[2025-08-07T18:02:34.133+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.access.key,*********(redacted))
[2025-08-07T18:02:34.133+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.attempts.maximum,20)
[2025-08-07T18:02:34.134+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.aws.credentials.provider,org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider)
[2025-08-07T18:02:34.134+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.connection.establish.timeout,60000)
[2025-08-07T18:02:34.134+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.connection.request.timeout,60000)
[2025-08-07T18:02:34.135+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.connection.ssl.enabled,false)
[2025-08-07T18:02:34.135+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.connection.timeout,60000)
[2025-08-07T18:02:34.135+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.endpoint,http://minio:9000)
[2025-08-07T18:02:34.135+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.impl,org.apache.hadoop.fs.s3a.S3AFileSystem)
[2025-08-07T18:02:34.135+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.path.style.access,true)
[2025-08-07T18:02:34.136+0000] {spark_submit.py:521} INFO - (spark.hadoop.fs.s3a.secret.key,*********(redacted))
[2025-08-07T18:02:34.136+0000] {spark_submit.py:521} INFO - (spark.jars,file:///opt/custom-jars/hadoop-aws-3.3.6.jar,file:///opt/custom-jars/aws-java-sdk-bundle-1.12.621.jar)
[2025-08-07T18:02:34.136+0000] {spark_submit.py:521} INFO - (spark.master,spark://spark-master:7077)
[2025-08-07T18:02:34.136+0000] {spark_submit.py:521} INFO - (spark.repl.local.jars,file:///opt/custom-jars/hadoop-aws-3.3.6.jar,file:///opt/custom-jars/aws-java-sdk-bundle-1.12.621.jar)
[2025-08-07T18:02:34.136+0000] {spark_submit.py:521} INFO - (spark.submit.deployMode,client)
[2025-08-07T18:02:34.136+0000] {spark_submit.py:521} INFO - (spark.submit.pyFiles,)
[2025-08-07T18:02:34.137+0000] {spark_submit.py:521} INFO - Classpath elements:
[2025-08-07T18:02:34.137+0000] {spark_submit.py:521} INFO - file:///opt/custom-jars/hadoop-aws-3.3.6.jar
[2025-08-07T18:02:34.137+0000] {spark_submit.py:521} INFO - file:///opt/custom-jars/aws-java-sdk-bundle-1.12.621.jar
[2025-08-07T18:02:34.137+0000] {spark_submit.py:521} INFO - 
[2025-08-07T18:02:34.137+0000] {spark_submit.py:521} INFO - 
[2025-08-07T18:02:37.115+0000] {spark_submit.py:521} INFO - Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
[2025-08-07T18:02:37.121+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO SparkContext: Running Spark version 4.0.0
[2025-08-07T18:02:37.124+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-08-07T18:02:37.125+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO SparkContext: Java version 17.0.15
[2025-08-07T18:02:37.158+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO ResourceUtils: ==============================================================
[2025-08-07T18:02:37.159+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-08-07T18:02:37.159+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO ResourceUtils: ==============================================================
[2025-08-07T18:02:37.160+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO SparkContext: Submitted application: test_s3a
[2025-08-07T18:02:37.211+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-08-07T18:02:37.217+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO ResourceProfile: Limiting resource is cpu
[2025-08-07T18:02:37.220+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-08-07T18:02:37.297+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO SecurityManager: Changing view acls to: ***
[2025-08-07T18:02:37.298+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO SecurityManager: Changing modify acls to: ***
[2025-08-07T18:02:37.299+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO SecurityManager: Changing view acls groups to: ***
[2025-08-07T18:02:37.299+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO SecurityManager: Changing modify acls groups to: ***
[2025-08-07T18:02:37.303+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: *** groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY; RPC SSL disabled
[2025-08-07T18:02:37.603+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO Utils: Successfully started service 'sparkDriver' on port 44235.
[2025-08-07T18:02:37.645+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO SparkEnv: Registering MapOutputTracker
[2025-08-07T18:02:37.661+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO SparkEnv: Registering BlockManagerMaster
[2025-08-07T18:02:37.677+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-08-07T18:02:37.678+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-08-07T18:02:37.682+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-08-07T18:02:37.717+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-e0920a79-d42d-45d3-a084-fe432c0f2950
[2025-08-07T18:02:37.755+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-08-07T18:02:37.894+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-08-07T18:02:37.968+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:37 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-08-07T18:02:38.003+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO SparkContext: Added JAR file:///opt/custom-jars/hadoop-aws-3.3.6.jar at spark://0d9cbc3d310d:44235/jars/hadoop-aws-3.3.6.jar with timestamp 1754589757107
[2025-08-07T18:02:38.003+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO SparkContext: Added JAR file:///opt/custom-jars/aws-java-sdk-bundle-1.12.621.jar at spark://0d9cbc3d310d:44235/jars/aws-java-sdk-bundle-1.12.621.jar with timestamp 1754589757107
[2025-08-07T18:02:38.025+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO SecurityManager: Changing view acls to: ***
[2025-08-07T18:02:38.026+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO SecurityManager: Changing modify acls to: ***
[2025-08-07T18:02:38.026+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO SecurityManager: Changing view acls groups to: ***
[2025-08-07T18:02:38.027+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO SecurityManager: Changing modify acls groups to: ***
[2025-08-07T18:02:38.027+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: *** groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY; RPC SSL disabled
[2025-08-07T18:02:38.186+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-08-07T18:02:38.239+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO TransportClientFactory: Successfully created connection to spark-master/172.19.0.3:7077 after 24 ms (0 ms spent in bootstraps)
[2025-08-07T18:02:38.430+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250807180238-0010
[2025-08-07T18:02:38.440+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 44573.
[2025-08-07T18:02:38.441+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO NettyBlockTransferService: Server created on 0d9cbc3d310d:44573
[2025-08-07T18:02:38.443+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-08-07T18:02:38.460+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250807180238-0010/0 on worker-20250807152928-172.19.0.5-46073 (172.19.0.5:46073) with 2 core(s)
[2025-08-07T18:02:38.465+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO StandaloneSchedulerBackend: Granted executor ID app-20250807180238-0010/0 on hostPort 172.19.0.5:46073 with 2 core(s), 1024.0 MiB RAM
[2025-08-07T18:02:38.471+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 0d9cbc3d310d, 44573, None)
[2025-08-07T18:02:38.475+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO BlockManagerMasterEndpoint: Registering block manager 0d9cbc3d310d:44573 with 434.4 MiB RAM, BlockManagerId(driver, 0d9cbc3d310d, 44573, None)
[2025-08-07T18:02:38.477+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 0d9cbc3d310d, 44573, None)
[2025-08-07T18:02:38.479+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 0d9cbc3d310d, 44573, None)
[2025-08-07T18:02:38.624+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-08-07T18:02:38.877+0000] {spark_submit.py:521} INFO - 25/08/07 18:02:38 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250807180238-0010/0 is now RUNNING
[2025-08-07T18:03:16.628+0000] {job.py:218} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 192, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/retries.py", line 89, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/retries.py", line 98, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 316, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-08-07T18:03:33.642+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-08-07T18:03:40.895+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:40 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-08-07T18:03:40.905+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:40 INFO SharedState: Warehouse path is 'file:/opt/***/spark-warehouse'.
[2025-08-07T18:03:43.072+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2025-08-07T18:03:43.114+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 INFO MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-08-07T18:03:43.116+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 INFO MetricsSystemImpl: s3a-file-system metrics system started
[2025-08-07T18:03:43.146+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 INFO MetricsSystemImpl: Stopping s3a-file-system metrics system...
[2025-08-07T18:03:43.150+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 INFO MetricsSystemImpl: s3a-file-system metrics system stopped.
[2025-08-07T18:03:43.150+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 INFO MetricsSystemImpl: s3a-file-system metrics system shutdown complete.
[2025-08-07T18:03:43.151+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 WARN FileSystem: Failed to initialize filesystem s3a://bronze/topcv/topcv_jobs.parquet: java.lang.NumberFormatException: For input string: "60s"
[2025-08-07T18:03:43.152+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: s3a://bronze/topcv/topcv_jobs.parquet.
[2025-08-07T18:03:43.152+0000] {spark_submit.py:521} INFO - java.lang.NumberFormatException: For input string: "60s"
[2025-08-07T18:03:43.153+0000] {spark_submit.py:521} INFO - at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[2025-08-07T18:03:43.153+0000] {spark_submit.py:521} INFO - at java.base/java.lang.Long.parseLong(Long.java:711)
[2025-08-07T18:03:43.153+0000] {spark_submit.py:521} INFO - at java.base/java.lang.Long.parseLong(Long.java:836)
[2025-08-07T18:03:43.153+0000] {spark_submit.py:521} INFO - at org.apache.hadoop.conf.Configuration.getLong(Configuration.java:1607)
[2025-08-07T18:03:43.153+0000] {spark_submit.py:521} INFO - at org.apache.hadoop.fs.s3a.S3AUtils.longOption(S3AUtils.java:985)
[2025-08-07T18:03:43.154+0000] {spark_submit.py:521} INFO - at org.apache.hadoop.fs.s3a.S3AFileSystem.initThreadPools(S3AFileSystem.java:785)
[2025-08-07T18:03:43.154+0000] {spark_submit.py:521} INFO - at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:555)
[2025-08-07T18:03:43.154+0000] {spark_submit.py:521} INFO - at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3615)
[2025-08-07T18:03:43.154+0000] {spark_submit.py:521} INFO - at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:172)
[2025-08-07T18:03:43.155+0000] {spark_submit.py:521} INFO - at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3716)
[2025-08-07T18:03:43.155+0000] {spark_submit.py:521} INFO - at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3667)
[2025-08-07T18:03:43.155+0000] {spark_submit.py:521} INFO - at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:557)
[2025-08-07T18:03:43.155+0000] {spark_submit.py:521} INFO - at org.apache.hadoop.fs.Path.getFileSystem(Path.java:366)
[2025-08-07T18:03:43.156+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:55)
[2025-08-07T18:03:43.156+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:381)
[2025-08-07T18:03:43.156+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.analysis.ResolveDataSource.org$apache$spark$sql$catalyst$analysis$ResolveDataSource$$loadV1BatchSource(ResolveDataSource.scala:143)
[2025-08-07T18:03:43.157+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.analysis.ResolveDataSource$$anonfun$apply$1.$anonfun$applyOrElse$2(ResolveDataSource.scala:61)
[2025-08-07T18:03:43.157+0000] {spark_submit.py:521} INFO - at scala.Option.getOrElse(Option.scala:201)
[2025-08-07T18:03:43.158+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.analysis.ResolveDataSource$$anonfun$apply$1.applyOrElse(ResolveDataSource.scala:61)
[2025-08-07T18:03:43.158+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.analysis.ResolveDataSource$$anonfun$apply$1.applyOrElse(ResolveDataSource.scala:45)
[2025-08-07T18:03:43.158+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$3(AnalysisHelper.scala:139)
[2025-08-07T18:03:43.158+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:86)
[2025-08-07T18:03:43.159+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$1(AnalysisHelper.scala:139)
[2025-08-07T18:03:43.159+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:416)
[2025-08-07T18:03:43.159+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning(AnalysisHelper.scala:135)
[2025-08-07T18:03:43.160+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning$(AnalysisHelper.scala:131)
[2025-08-07T18:03:43.161+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUpWithPruning(LogicalPlan.scala:37)
[2025-08-07T18:03:43.161+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp(AnalysisHelper.scala:112)
[2025-08-07T18:03:43.161+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp$(AnalysisHelper.scala:111)
[2025-08-07T18:03:43.162+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUp(LogicalPlan.scala:37)
[2025-08-07T18:03:43.163+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.analysis.ResolveDataSource.apply(ResolveDataSource.scala:45)
[2025-08-07T18:03:43.163+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.analysis.ResolveDataSource.apply(ResolveDataSource.scala:43)
[2025-08-07T18:03:43.164+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:242)
[2025-08-07T18:03:43.165+0000] {spark_submit.py:521} INFO - at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
[2025-08-07T18:03:43.165+0000] {spark_submit.py:521} INFO - at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)
[2025-08-07T18:03:43.166+0000] {spark_submit.py:521} INFO - at scala.collection.immutable.List.foldLeft(List.scala:79)
[2025-08-07T18:03:43.166+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:239)
[2025-08-07T18:03:43.166+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:231)
[2025-08-07T18:03:43.167+0000] {spark_submit.py:521} INFO - at scala.collection.immutable.List.foreach(List.scala:334)
[2025-08-07T18:03:43.168+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:231)
[2025-08-07T18:03:43.168+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.analysis.Analyzer.org$apache$spark$sql$catalyst$analysis$Analyzer$$executeSameContext(Analyzer.scala:290)
[2025-08-07T18:03:43.169+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$execute$1(Analyzer.scala:286)
[2025-08-07T18:03:43.170+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.analysis.AnalysisContext$.withNewAnalysisContext(Analyzer.scala:234)
[2025-08-07T18:03:43.170+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:286)
[2025-08-07T18:03:43.171+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:249)
[2025-08-07T18:03:43.171+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:201)
[2025-08-07T18:03:43.172+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:89)
[2025-08-07T18:03:43.172+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:201)
[2025-08-07T18:03:43.172+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.resolveInFixedPoint(HybridAnalyzer.scala:190)
[2025-08-07T18:03:43.173+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$apply$1(HybridAnalyzer.scala:76)
[2025-08-07T18:03:43.173+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.withTrackedAnalyzerBridgeState(HybridAnalyzer.scala:111)
[2025-08-07T18:03:43.173+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.apply(HybridAnalyzer.scala:71)
[2025-08-07T18:03:43.174+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:280)
[2025-08-07T18:03:43.174+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:423)
[2025-08-07T18:03:43.175+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:280)
[2025-08-07T18:03:43.175+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$2(QueryExecution.scala:110)
[2025-08-07T18:03:43.175+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:148)
[2025-08-07T18:03:43.176+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:278)
[2025-08-07T18:03:43.176+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:654)
[2025-08-07T18:03:43.176+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:278)
[2025-08-07T18:03:43.177+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:804)
[2025-08-07T18:03:43.177+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:277)
[2025-08-07T18:03:43.177+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$1(QueryExecution.scala:110)
[2025-08-07T18:03:43.177+0000] {spark_submit.py:521} INFO - at scala.util.Try$.apply(Try.scala:217)
[2025-08-07T18:03:43.178+0000] {spark_submit.py:521} INFO - at org.apache.spark.util.Utils$.doTryWithCallerStacktrace(Utils.scala:1378)
[2025-08-07T18:03:43.178+0000] {spark_submit.py:521} INFO - at org.apache.spark.util.LazyTry.tryT$lzycompute(LazyTry.scala:46)
[2025-08-07T18:03:43.178+0000] {spark_submit.py:521} INFO - at org.apache.spark.util.LazyTry.tryT(LazyTry.scala:46)
[2025-08-07T18:03:43.179+0000] {spark_submit.py:521} INFO - at org.apache.spark.util.LazyTry.get(LazyTry.scala:58)
[2025-08-07T18:03:43.180+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:121)
[2025-08-07T18:03:43.181+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:80)
[2025-08-07T18:03:43.182+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.classic.Dataset$.$anonfun$ofRows$1(Dataset.scala:115)
[2025-08-07T18:03:43.183+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:804)
[2025-08-07T18:03:43.184+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.classic.Dataset$.ofRows(Dataset.scala:113)
[2025-08-07T18:03:43.184+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.classic.DataFrameReader.load(DataFrameReader.scala:109)
[2025-08-07T18:03:43.185+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.classic.DataFrameReader.load(DataFrameReader.scala:58)
[2025-08-07T18:03:43.185+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:457)
[2025-08-07T18:03:43.186+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.classic.DataFrameReader.parquet(DataFrameReader.scala:306)
[2025-08-07T18:03:43.186+0000] {spark_submit.py:521} INFO - at org.apache.spark.sql.classic.DataFrameReader.parquet(DataFrameReader.scala:58)
[2025-08-07T18:03:43.187+0000] {spark_submit.py:521} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-08-07T18:03:43.187+0000] {spark_submit.py:521} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-08-07T18:03:43.188+0000] {spark_submit.py:521} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-08-07T18:03:43.188+0000] {spark_submit.py:521} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-08-07T18:03:43.189+0000] {spark_submit.py:521} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-08-07T18:03:43.189+0000] {spark_submit.py:521} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-08-07T18:03:43.189+0000] {spark_submit.py:521} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2025-08-07T18:03:43.190+0000] {spark_submit.py:521} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-08-07T18:03:43.191+0000] {spark_submit.py:521} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-08-07T18:03:43.192+0000] {spark_submit.py:521} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:184)
[2025-08-07T18:03:43.193+0000] {spark_submit.py:521} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:108)
[2025-08-07T18:03:43.194+0000] {spark_submit.py:521} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2025-08-07T18:03:43.195+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2025-08-07T18:03:43.196+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 INFO MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-08-07T18:03:43.197+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 INFO MetricsSystemImpl: s3a-file-system metrics system started
[2025-08-07T18:03:43.199+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 INFO MetricsSystemImpl: Stopping s3a-file-system metrics system...
[2025-08-07T18:03:43.200+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 INFO MetricsSystemImpl: s3a-file-system metrics system stopped.
[2025-08-07T18:03:43.200+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 INFO MetricsSystemImpl: s3a-file-system metrics system shutdown complete.
[2025-08-07T18:03:43.201+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 WARN FileSystem: Failed to initialize filesystem s3a://bronze/topcv/topcv_jobs.parquet: java.lang.NumberFormatException: For input string: "60s"
[2025-08-07T18:03:43.396+0000] {spark_submit.py:521} INFO - Traceback (most recent call last):
[2025-08-07T18:03:43.403+0000] {spark_submit.py:521} INFO - File "/opt/spark-jobs/gold_transform.py", line 4, in <module>
[2025-08-07T18:03:43.404+0000] {spark_submit.py:521} INFO - df = spark.read.parquet("s3a://bronze/topcv/topcv_jobs.parquet")
[2025-08-07T18:03:43.405+0000] {spark_submit.py:521} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-07T18:03:43.405+0000] {spark_submit.py:521} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 642, in parquet
[2025-08-07T18:03:43.416+0000] {spark_submit.py:521} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/py4j-0.10.9.9-src.zip/py4j/java_gateway.py", line 1362, in __call__
[2025-08-07T18:03:43.418+0000] {spark_submit.py:521} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 288, in deco
[2025-08-07T18:03:43.437+0000] {spark_submit.py:521} INFO - pyspark.errors.exceptions.captured.NumberFormatException: For input string: "60s"
[2025-08-07T18:03:43.895+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 INFO SparkContext: Invoking stop() from shutdown hook
[2025-08-07T18:03:43.901+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 INFO SparkContext: SparkContext is stopping with exitCode 0 from run at Executors.java:539.
[2025-08-07T18:03:43.916+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 INFO SparkUI: Stopped Spark web UI at http://0d9cbc3d310d:4040
[2025-08-07T18:03:43.919+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-08-07T18:03:43.925+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-08-07T18:03:43.944+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:43 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-08-07T18:03:44.024+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:44 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-08-07T18:03:44.025+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:44 INFO MemoryStore: MemoryStore cleared
[2025-08-07T18:03:44.025+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:44 INFO BlockManager: BlockManager stopped
[2025-08-07T18:03:44.038+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:44 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-08-07T18:03:44.041+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:44 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-08-07T18:03:44.053+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:44 INFO SparkContext: Successfully stopped SparkContext
[2025-08-07T18:03:44.054+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:44 INFO ShutdownHookManager: Shutdown hook called
[2025-08-07T18:03:44.055+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:44 INFO ShutdownHookManager: Deleting directory /tmp/spark-4ea8c7d8-a062-4110-82de-a976890390a0
[2025-08-07T18:03:44.061+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:44 INFO ShutdownHookManager: Deleting directory /tmp/spark-d5674647-21c4-4e3f-b6a1-ee13a3e96805/pyspark-e058554c-0d29-412f-86a5-ea6ad6fc0ec4
[2025-08-07T18:03:44.067+0000] {spark_submit.py:521} INFO - 25/08/07 18:03:44 INFO ShutdownHookManager: Deleting directory /tmp/spark-d5674647-21c4-4e3f-b6a1-ee13a3e96805
[2025-08-07T18:03:44.124+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-07T18:03:44.269+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 452, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=minioadmin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --conf spark.hadoop.fs.s3a.connection.ssl.enabled=false --conf spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider --conf spark.hadoop.fs.s3a.connection.timeout=60000 --conf spark.hadoop.fs.s3a.connection.establish.timeout=60000 --conf spark.hadoop.fs.s3a.connection.request.timeout=60000 --conf spark.hadoop.fs.s3a.attempts.maximum=20 --jars /opt/custom-jars/hadoop-aws-3.3.6.jar,/opt/custom-jars/aws-java-sdk-bundle-1.12.621.jar --name arrow-spark --verbose /opt/spark-jobs/gold_transform.py. Error code is: 1.
[2025-08-07T18:03:44.288+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spark_transform_topcv, task_id=submit_spark_job, run_id=manual__2025-08-07T18:02:19.243923+00:00, execution_date=20250807T180219, start_date=20250807T180227, end_date=20250807T180344
[2025-08-07T18:03:44.307+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 89 for task submit_spark_job (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=minioadmin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --conf spark.hadoop.fs.s3a.connection.ssl.enabled=false --conf spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider --conf spark.hadoop.fs.s3a.connection.timeout=60000 --conf spark.hadoop.fs.s3a.connection.establish.timeout=60000 --conf spark.hadoop.fs.s3a.connection.request.timeout=60000 --conf spark.hadoop.fs.s3a.attempts.maximum=20 --jars /opt/custom-jars/hadoop-aws-3.3.6.jar,/opt/custom-jars/aws-java-sdk-bundle-1.12.621.jar --name arrow-spark --verbose /opt/spark-jobs/gold_transform.py. Error code is: 1.; 244)
[2025-08-07T18:03:44.335+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-07T18:03:44.356+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-07T18:03:44.358+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
